version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: python padfoot_src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/padfoot_src  
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}


volumes:
  postgres_data: